UIA_ Enums
microsoft/win32metadata pull request #1251
Opened 2022-09-14 22:51 UTC by chenss3

Fixes: #1074 

Metadata diff:
```
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES added
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES.AnnotationType_AdvancedProofingIssue added
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES.AnnotationType_Author added
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES.AnnotationType_CircularReferenceError added
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES.AnnotationType_Comment added
Windows.Win32.System.SystemServices.UIA_ANNOTATIONTYPES.AnnotationType_ConflictingChange added
[....Omitting 800 lines.....]
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesExtendedPropertiesPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesFillColorPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesFillPatternColorPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesFillPatternStylePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesShapePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesStyleIdPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_StylesStyleNamePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TableColumnHeadersPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TableItemColumnHeaderItemsPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TableItemRowHeaderItemsPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TableRowHeadersPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TableRowOrColumnMajorPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_ToggleToggleStatePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_Transform2CanZoomPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_Transform2ZoomLevelPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_Transform2ZoomMaximumPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_Transform2ZoomMinimumPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TransformCanMovePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TransformCanResizePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_TransformCanRotatePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_ValueIsReadOnlyPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_ValueValuePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_VisualEffectsPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowCanMaximizePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowCanMinimizePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowIsModalPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowIsTopmostPropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowWindowInteractionStatePropertyId added
Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_WindowWindowVisualStatePropertyId added
Windows.Win32.UI.Accessibility.UiaPropertyChangedEventArgs.EventId...System.Int32 => Windows.Win32.UI.Accessibility.UIA_EVENT_ID
Windows.Win32.UI.Accessibility.UiaPropertyCondition.PropertyId...System.Int32 => Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID
```

2022-09-14 22:54 UTC, mikebattista requested changes

2022-09-14 22:54 UTC, mikebattista commented on generation/WinSDK/enums.json
> +    "name": "UIA_ANNOTATIONTYPES",
Make singular.

2022-09-19 21:10 UTC, mikebattista approved these changes

2022-09-19 21:11 UTC, merged

2023-10-11 18:48 UTC, Tanya-Solyanik commented
@chenss3  - this PR had added control types as an unsigned type - 
![image](https://github.com/microsoft/win32metadata/assets/15823268/896937f4-5ac9-4965-bd62-b1ff560d5d42)

However, the idl defines them as signed - UIAutomationClient.idl

```
 [dllname("<no entry points>")]
    module UIA_ControlTypeIds
    {
        const long UIA_ButtonControlTypeId        = 50000;
        const long UIA_CalendarControlTypeId      = 50001;
```

This looks like a bug to me.