Add attribute on IPropertyStoreCapabilities::IsPropertyWritable
microsoft/win32metadata pull request #1942
Opened 2024-07-05 20:18 UTC by riverar

Fixes: #1941

Adds `CanReturnMultipleSuccessValuesAttribute` to `IPropertyStoreCapabilities::IsPropertyWritable` method. This method can return either `S_OK` or `S_FALSE`.

2024-07-05 20:37 UTC, AArnott submitted a review, later dismissed
Thanks!

2024-07-08 16:08 UTC, mikebattista requested changes
You don't need the "-Attribute" suffix here and we don't use it elsewhere in this file. Please remove it for consistency.

2024-07-08 16:13 UTC, riverar commented
Oh I cut/pasted it from earlier in the file (GetMessage). Will fix.

2024-07-08 16:36 UTC, mikebattista approved these changes
Thanks.

2024-07-08 16:36 UTC, merged