GitHub: Improved README.md and added issue templates
microsoft/win32metadata pull request #1954
Opened 2024-07-31 14:26 UTC by 0x5bfa

2024-07-31 15:56 UTC, getrou commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Built to validate chnages
typo - changes

2024-07-31 22:12 UTC, 0x5bfa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Built to validate chnages
Thanks, fixed.

2024-08-16 16:13 UTC, riverar commented
Not sure about these changes, especially those that create more overhead in our issues/PR workflows (e.g., like requiring we check some box indicating we've tested locally).

2024-08-16 16:15 UTC, riverar requested changes
Not sure about these changes, especially those that create more overhead in our issues/PR workflows (e.g., like requiring we check some box indicating we've tested locally).

I think we can limit the changes to doc tweaks and `.github` consolidation, but we'll need to double check the backend doesn't have any dependencies there.

2024-08-16 17:05 UTC, 0x5bfa commented
I deleted PR template. Yet honestly I'd find issue templates very useful, what do you think? If not needed, I'd delete them.

I added the clear header in the readme and tweaked some.

2024-08-23 10:41 UTC, closed without merging